### ISSUE TITLE
"npm run nxt"   error 

### ISSUE THREAD

**Issue by HexaHash** [sandoche/Proof-of-Stake-Cryptocurrency-generator#11]
> proof-of-stake-cryptocurrency-generator@1.0.0 nxt C:\Users\Hexa\Desktop\HexaHa    sh-Crypto
> cd nxt ; sh ./compile.sh ; sh ./run.sh

Le chemin d'acc▒s sp▒cifi▒ est introuvable.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! proof-of-stake-cryptocurrency-generator@1.0.0 nxt: `cd nxt ; sh ./compi    le.sh ; sh ./run.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the proof-of-stake-cryptocurrency-generator@1.0.0 nxt script.
npm ERR! This is probably not a problem with npm. There is likely additional log    ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Hexa\AppData\Roaming\npm-cache\_logs\2018-05-08T17_06_11_0    12Z-debug.log

**Comment by sandoche** [comment]
What is your node version? It is required to have a version >= 8.0.
Otherwise what you can do is to go to the nxt folder, then run `sh ./compile.sh` followed by `sh ./run.sh`

**Comment by sandoche** [comment]
In case of windows go in the "nxt" folder then run `sh ./win-compile.sh` then run `run.bat`

**Comment by sandoche** [comment]
I use the git bash, but I guess than Power shell would do it too

**Comment by HexaHash** [comment]
I have a fix: Need to run  "run.bat"

**Comment by Yonton** [comment]
Yes , Running .bat file worked lmao. I Stupid Newbie 😂

**Comment by Cryptoconnect2019** [comment]
hmm is that needed to call someone stupid newbie?  no need for that Yonton ;-)
