### ISSUE TITLE
Genesis Block creation

### ISSUE THREAD

**Issue by BardoBravo** [sandoche/Proof-of-Stake-Cryptocurrency-generator#13]
Hello,

Whenever I try to do the part 6 of step 1 ("Go to http://localhost:7876/test?requestTag=ADDONS click on "downloadJPLSnapshot" then upload your file "newGenesisAccounts.json"...") I get the following error message:

{"errorDescription":"Inceorrect \"height\"","errorCode":4}

Could you help on this?

**Comment by HexaHash** [comment]
Try to actualize the height or re sync the blockchain.

**Comment by BardoBravo** [comment]
Hi,
It worked when I downloaded all the blockchain again.
Hugs
