### ISSUE TITLE
NXT creation Account

### ISSUE THREAD

**Issue by chopin2712** [sandoche/Proof-of-Stake-Cryptocurrency-generator#22]
Dear

I typed this command : 
npm run nxt

But the number of Minutes left increase at every actions. And I don't now how many times It takes. So
I tried to create a Account. When I created my account it say : 
Connecting to the network, please try again later.

What should I do ?

Thanks

**Comment by chopin2712** [comment]
282 minutes left XD

**Comment by sandoche** [comment]
So I guess you managed?

**Comment by sandoche** [comment]
To create your account try to reopen the wallet in private navigation.
The full sync of the wallet can be long yes.
