### ISSUE TITLE
Wallet Address Never loads: Cannot Register

### ISSUE THREAD

**Issue by aaroncatalano** [sandoche/Proof-of-Stake-Cryptocurrency-generator#23]
Execute npm run nxt  on Ubuntu 18. After fully downloading the blockchain, I launch the URL to register: 
http://localhost:7876/index.html

Bug:
Page never loads successfully. Message displayed: Cannot connect to /nxt-proxy No openAPI peers found

Tried both Private and Public browser connections in Chrome/Firefox

**Comment by sandoche** [comment]
Can you copy paste the logs from your console here?

**Comment by aaroncatalano** [comment]
I was never able to the get Wallet to work on Ubuntu 18. Wallet displays/Works on Winodw 7 running linux add on.
