### ISSUE TITLE
Android Wallet?

### ISSUE THREAD

**Issue by Noiden** [sandoche/Proof-of-Stake-Cryptocurrency-generator#28]
Not really an issue, more of a request.

Is there some Android Wallet you can use for your own blockchain created with this?

Thanks.

**Comment by sandoche** [comment]
Actually in the generated folder you will see a "mobile" folder that contains the source of an Android app using cordova. I didn't try it so I cannot guide you on the process.

Also you can try to contact the maker of this wallet to add your coin : https://walletnxt.com/
Or directly fork their Github to make it by yourself!

**Comment by Noiden** [comment]
Ok, will try that mobile folder and thanks for the fork suggestion. =)
