### ISSUE TITLE
cannot connect to /nxt-proxy no openAPI peers found

### ISSUE THREAD

**Issue by mathiasvanheule** [sandoche/Proof-of-Stake-Cryptocurrency-generator#29]
After compiling with  .\win-compile.sh and syncing the chain with .\run.bat I've created an account on http://localhost:7876/index.html. Though when trying to login it keeps saying either "cannot connect to /nxt-proxy no openAPI peers found" or
"Connecting to the network... Please try again later." I get the same output in the logging of the terminal:
cannot connect to /nxt-proxy no openAPI peers found
but this is followed by "looking for remote confirmation nodes"
"updating remote nodes"
and I can see it is actually syncing.

To get around this issue I've tried both installing the windows wallet as a light client and full node. But there I have the same issue.
I've tried both on windows and ubuntu. I've tried firefox, chrome, IE and also private prowser tabs but I always get the same error.
Also, because I installed the wallet as a full node, when I tried running the run.bat file now I get the error that the chain is corrupt/newer. So I guess i'll have to delete the NXT database from my appdata/roaming folder and re-sync with run.bat?
Any ideas on how to login to the wallet?

**Comment by sandoche** [comment]
Hi, have you tried the following:
https://github.com/sandoche/Proof-of-Stake-Cryptocurrency-generator#troubleshooting

Also try it with Git bash instead of the normal terminal.

**Comment by mathiasvanheule** [comment]
I managed to get the public key with the API documentation and after setting up the chain entirely with my own nodes, I didn't have this issue anymore. Private browser is also not needed now. Thank you!
