### ISSUE TITLE
Make transfer anything without Fee

### ISSUE THREAD

**Issue by ibnumaksum** [sandoche/Proof-of-Stake-Cryptocurrency-generator#33]
Can we create this coin without any fee for transfer or anything?

Zero fee

Where do i change it?

**Comment by sandoche** [comment]
I haven't tried but I guess you can do it here: https://github.com/sandoche/Proof-of-Stake-Cryptocurrency-generator/blob/54c7fb4ad5e3fef60cdb8072fc7654f6a8a755f1/nxt/src/java/nxt/Fee.java

Maybe by setting `DEFAULT_FEE = NONE` I haven't tried and I guess there is a easier way.

**Comment by ibnumaksum** [comment]
i am success with without fee.

need to change many files, because of division by Zero
change ONE_NXT in Constants.java
then find any mention Constants.ONE_NXT, and check if it division by Constants.ONE_NXT
some i change to 1, some just delete it

my changes
https://github.com/Zentriazan/zent/commit/03c0dea15d3b79731c6d6a139a8ceae231965bfd
