### ISSUE TITLE
NXT Client needs update (1.12.2)

### ISSUE THREAD

**Issue by Aeris1One** [sandoche/Proof-of-Stake-Cryptocurrency-generator#40]
I've got some logs saying "Your peer has been blacklisted" "Cause : Old Version".
Can you please upgrade the client to its latest version ? (Maybe also NXT-Clone-Starter)

**Comment by Aeris1One** [comment]
I'll try asap

**Comment by Aeris1One** [comment]
Works perfectly ! I think you can upgrade

**Comment by sandoche** [comment]
I'll do it when I find a bit of time thanks.

**Comment by sandoche** [comment]
Done
