### ISSUE TITLE
downloadJPLSnapshot dosnt exist

### ISSUE THREAD

**Issue by 0xnim** [sandoche/Proof-of-Stake-Cryptocurrency-generator#49]
it is just not there as well as ADDOONS section. what is the otehr way to go on?

**Comment by 0xnim** [comment]
Yea still dosnt work even after changin the nxt.properties file

**Comment by 0xnim** [comment]
How to fix it?

**Comment by sandoche** [comment]
Have you followed this?
https://bitbucket.org/Jelurida/nxt-clone-starter/src/master/

**Comment by 0xnim** [comment]
yes

**Comment by 0xnim** [comment]
It does not take effect

**Comment by Toxiapo** [comment]
What I did was skip step 3 from the guide, and download the NXT client directly from the official site. 
https://bitbucket.org/Jelurida/nxt/downloads/ 

OPTIONAL: Download the latest database, and replace the nxt_db folder, so you don't need to resync the blockchain. https://www.jelurida.com/NXT-nxt_db.zip

Enable the JPLSnapshot add-on in conf/nxt.properties by setting:

nxt.addOns=nxt.addons.JPLSnapshot

Compile and run. 

You should see it in http://localhost:7876/test?requestTag=ADDONS

**Comment by 0xnim** [comment]
ok

**Comment by 0xnim** [comment]
will try when avalable

**Comment by 0xnim** [comment]
If i do the default from bitbuclet then will i just drag the files into the folder?

**Comment by Toxiapo** [comment]
Yes, you can drag the files into the nxt folder if you want.
