### ISSUE TITLE
Why charge 10% if nothing is guaranteed in return

### ISSUE THREAD

**Issue by alolalo** [sandoche/Proof-of-Stake-Cryptocurrency-generator#66]
Hi there,

I really would like to say thank you first, nothing cold or harshness here that vents. I just think that the smart contract here is the 10%, not the blockchain.

It's the only contract that states a centralized authority that, when you think about Web 3.0's decentralized autonomous spirit, makes no sense; nothing is mined for the 10% in the first place, not even a non-fungible guarantee it will "always work".

It's just there, and to my knowledge doesn't make it work any better if it's decentralized under another cryptocurrency, that is then decentralized on Ethereum and such. It's just a smart contract because it's first, not because it's fungible.

With regards,
Guus

**Comment by sandoche** [comment]
The 10% is part of the JPL license: https://www.jelurida.com/resources/jpl
